#theme: modernist
collections:
  authors:
    output: true
  wikipages:
    output: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
